= Image Recognition addon

This addon extracts the content of your images, using Google Vision API,
and index it in order to allow to search images by their content.

== Installation

At the root of your eXo Platform distribution, execute:

`./addon install exo-image-recognition`

=== Google Vision API

This addon relies on Google Vision API for image recognition. You must first configure the API access:

* Go to the https://console.cloud.google.com/apis/credentials/serviceaccountkey[Create service account key page] in the GCP Console.
* From the `Service account` drop-down list, select `New service account`.
* Enter a name into the `Service account name` field.
* Don't select a value from the `Role` drop-down list, no role is required to access this service.
* Click `Create`. A note appears, warning that this service account has no role.
* Click `Create without role`. A JSON file that contains your key downloads to your computer.

WARNING: Google Vision API gives a free quota of 1000 requests/month, then it is billed on usage.

==== eXo Platform

* in eXo, rename the file `bin/setenv-customize.sample.(sh|bat)` to `bin/setenv-customize.(sh|bat)`
* At the end of the file adds:
** `export GOOGLE_APPLICATION_CREDENTIALS=<path to the json file>` for Linux
** `SET GOOGLE_APPLICATION_CREDENTIALS=<path to the json file>` for Windows
* Start eXo

== Configuration

Google Vision API returns a list of labels related to the given image, with a relevancy score.
This relevancy goes from 0 to 1 (1 being the highest).
By default, the addon adds the labels with a relevancy score greater than 0.75 to the image.
This threshold can be changed by setting the parameter `exo.image.recognition.label.threshold` in the file `exo.properties`.

== Usage

Once eXo started, upload some images.
You should be able to find your images by their content u=in the unified search.
